### PR TITLE
Added Weather App UI

### PR DESCRIPTION
**Pull request by valentineg8**
## Submission description

- Ui snippets
  Weather App UI

### CODE REVIEW

**Comment by jfversluis** [comment]
Hey @attrib75 our unit test is failing on your expired cert for the website. Are you aware of this? :)

**Comment by attrib75** [comment]
> 
> 
> Hey @attrib75 our unit test is failing on your expired cert for the website. Are you aware of this? :)

Hi, thanks for letting me know.  I'm in the middle of trying to migrate this hosting, cert and dns.  Hopefully will be resolved soon.

**Comment by attrib75** [comment]
Ok this should be fixed now.  I've secured the cert for the site.  Thanks!

**Comment by jfversluis** [comment]
Seems to work now! Thanks!

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
