### PR TITLE
Facebook Mobile App Login UI Clone

### PR DESCRIPTION
**Pull request by ShahrukhYousafzai**
*Thanks for submitting a PR to the Snppts ✂️ library!*

## Submission description

Facebook Mobile App Login UI Clone in Xamarin Forms.
Facebook Mobile App Login UI

### Possible platform improvements

_Missing something on the platform? Let us know here._

### CODE REVIEW

**Review by jfversluis — CHANGES_REQUESTED** [review]
It seems there is a build error, could you please fix that? :)

Thanks!

**Comment by ShahrukhYousafzai** [comment]
Yes, Please check now :) 
Thanks!

**Review by jfversluis — APPROVED** [review]
Build succeeded, thank you for you contribution!

**Comment by sthewissen** [comment]
Thanks for contributing to Snppts! Please fill in the following survey to receive your swag :)

https://www.surveymonkey.com/r/88ZQ6G2

**Pull request merged**
