### PR TITLE
Added unit tests

### PR DESCRIPTION
**Pull request by ionixjunior**
## Some unit tests added

In https://github.com/snpptsdev/snppts/issues/18 @jfversluis suggest create some tests for the project. So, here is it!

To run the tests execute in the command line `dotnet test src/Snppts.Tests` or use Visual Studio to do this. Maybe take a while to run all because all the repositories and images URIs are requested.

The unit test project was build with NUnit and target framework is the same of the main project - .NET Core 2.2.

Now the tests can be added in the pipeline! 
I hope this can be useful.

### CODE REVIEW

**Comment by jfversluis** [comment]
Oooh that is awesome! Thank you so much! :D 

The pipeline is YAML, right? Any reason you didn't add it to that yet? :)

**Comment by sthewissen** [comment]
That in and of itself is a reason, no? :D

**Comment by ionixjunior** [comment]
The unit tests is already integrated in Azure Pipelines! I didn't need to configure anything.

Pipeline information below:
image

**Comment by jfversluis** [comment]
Oh you are right! 😅 wonderful!

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
