### PR TITLE
Create AvatarLogin

### PR DESCRIPTION
**Pull request by aimore**
Is .gif acceptable?

### CODE REVIEW

**Comment by sthewissen** [comment]
I can't find the repo you provided. Also I think we'd rather not allow GIF, seeing as how they can drastically increase loading times depending on how big they are. What's your take on that @jfversluis?

**Comment by aimore** [comment]
Sorry I just changed the repo to public, you should be able to see it now

**Comment by jfversluis** [comment]
I must agree with Steven, I'd rather stick with PNG or JPG or non animated GIF for that matter. GIFs can easily take up multiple megabytes which would negatively impact the user experience. If you could swap it out for a different image I think we are good to go :)

**Review by sthewissen — APPROVED** [review]

**Comment by aimore** [comment]
Would be nice to show somehow the app animations.
Linking to a video since embedded videos would be even "heavier" than displaying a small gif.

**Pull request merged**
