### PR TITLE
Author Profile

### PR DESCRIPTION
**Pull request by logeshpalani33**
Pulling Author profile

*Thanks for submitting a PR to the Snppts ✂️ library!*

## Submission description

_Use this area to describe your submission. Screenshots are appreciated and GIFs (with a hard "g") will get bonus points!_

### Possible platform improvements

_Missing something on the platform? Let us know here._

### CODE REVIEW

**Comment by jfversluis** [comment]
Hey @logeshpalani98 thanks for your PR!

Just as an FYI to prevent any misunderstandings, just adding yourself as an author without any snippet will not count towards the challenge. Thanks!

**Comment by logeshpalani33** [comment]
As soon as possible, I will update my snippet @jfversluis and thanks

**Comment by logeshpalani33** [comment]
@jfversluis my first snippet sample added

**Comment by jfversluis** [comment]
Build fails 

> Error CS0117: 'Category' does not contain a definition for 'Login'

**Comment by logeshpalani33** [comment]
@jfversluis now fixed check it.

**Pull request closed without merging**
