### PR TITLE
PokeApp

### PR DESCRIPTION
**Pull request by kainaalmeida**
*Thanks for submitting a PR to the Snppts ✂️ library!*

## Submission description

Add poke to snnpts

### CODE REVIEW

**Comment by jfversluis** [comment]
You only mention PokeApp but I also see a salon app? Is that correct?

**Comment by kainaalmeida** [comment]
Now I'm going up another example that I did, that no case is pokeapp, or salon I did a while ago

**Comment by kainaalmeida** [comment]
the beauty salon app is already part of the snnpts

**Comment by jfversluis** [comment]
Yet your author class and salon were in this pr. But I fixed it for you :)

**Comment by kainaalmeida** [comment]
Oh, sorry. Thanks :)

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
