### PR TITLE
Fixed current logic issues in sorting and also added API-fy capabilities

### PR DESCRIPTION
**Pull request by naweed**
To test the APIs:

https://snppts.dev/api/v.1.0/snippets/latest
https://snppts.dev/api/v.1.0/snippets/top
https://snppts.dev/api/v.1.0/category/1
https://snppts.dev/api/v.1.0/author/naweed

### CODE REVIEW

**Comment by naweed** [comment]
@jfversluis here you go....

**Comment by naweed** [comment]
@jfversluis why did the checks fail?

**Comment by jfversluis** [comment]
Was a broken link, fixed now! I'll have a look at this soon :)

**Comment by naweed** [comment]
Great.

**Pull request closed without merging**
