### PR TITLE
Added naweed-maui-apps

### PR DESCRIPTION
**Pull request by naweed**
Added a couple of my .Net Maui apps.

### CODE REVIEW

**Comment by naweed** [comment]
Plz ignore launchSetting file from the commit. I submitted by mistake.

**Comment by jfversluis** [comment]
> Plz ignore launchSetting file from the commit. I submitted by mistake.

I can't ignore it unless you discard the changes :D

**Comment by naweed** [comment]
Removed. Thanks

**Comment by jfversluis** [comment]
Now it's deleted which is also not what we want to do 😬

**Comment by naweed** [comment]
Ok, let me discard the whole PR.. I will submit a new one.

**Pull request closed without merging**
