### PR TITLE
Xamarin Forms Dark Store UI Design

### PR DESCRIPTION
**Pull request by ufukhawk**
Xamarin Forms Dark Store UI Design

*Thanks for submitting a PR to the Snppts ✂️ library!*

## Submission description

_Use this area to describe your submission. Screenshots are appreciated and GIFs (with a hard "g") will get bonus points!_

### Possible platform improvements

_Missing something on the platform? Let us know here._

### CODE REVIEW

**Review by ufukhawk — COMMENTED** [review]
update

**Comment by jfversluis** [comment]
PR number 100! Congratulations! You win our forever gratefulness 🙏 and rights to open more PRs 😄

**Review by jfversluis — APPROVED** [review]

**Comment by jfversluis** [comment]
Hm looks like build fails because of a problem in the pipeline. I will look at it a little later. Sorry for the trouble!

**Comment by ufukhawk** [comment]
Thank you! 😂

**Pull request merged**
