### PR TITLE
Add feature to sort snppts

### PR DESCRIPTION
**Pull request by alexandresanlim**
### This feature add sort possible to snppts
image

### Stars result:
image

### Recent result:
image

## How to do?
I have use the [github api](https://developer.github.com/v3/search/#search-repositories) to get stars and updated data from GitHubRepoName informated by user.

## Notes
- Modify old system?
Not! The unique modificaion is how to set repo info from author:
`public string GithubRepoName => "snpptsio/Snppts.PinBasedLogin";`
to
`public GitHubRepoInfo GitHubRepoInfo => new GitHubRepoInfo("snpptsio/Snppts.PinBasedLogin");`

- The call api is heavy?
Not! is created a unique call with 30 result per page (default github api)

- If the api can't get informations from snppt repo info?
This snnpts is not show in results but it just happens when GitHubRepoName information is wrong,

I have try create a test to identity this with a test project but i don't know get all snppts in test mine :/
```
namespace SnpptsTests
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestPossibleInconsistencyRepoName()
        {
            var a = type.Assembly.GetTypes()
                .Where(x => typeof(IAmASnippet).IsAssignableFrom(x) && !x.IsInterface && !x.IsAbstract).ToList();
                .Select(x => x.GetInterfaces());
                .ToList();
        }
    }
}
```
Well guys is it.

### CODE REVIEW

**Comment by jfversluis** [comment]
Awesome! Great idea :) 

Looks like this branch isn't up-to-date with the latest master though.

**Comment by sthewissen** [comment]
Also, please correct the styling on the GitHub stars in the overview. The font should match the rest of the site :) And from the looks of your screenshots when sorting on most recent the header says "Stars snippets" which doesn't seem right.

Great idea though, that's for sure :)

**Comment by alexandresanlim** [comment]
@jfversluis @sthewissen Great infos!

# On new push is solved:
- **Get latest snppts master branch**

- **Sort title**

image

- **Star style overview**

image

**Comment by jfversluis** [comment]
So sorry. Another PR was merged so this branch is out of date again :( if you can update it I will make sure to look at it right away!

**Comment by alexandresanlim** [comment]
Up this branch from master, but i have a problem when run on local machine mine the tests created by @ionixjunior :
```

The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[13540] testhost.x86.exe' has exited with code -2147450730 (0x80008096).
```

image

**Comment by jfversluis** [comment]
It runs successfully on the pipeline so don't worry :)

**Review by jfversluis — APPROVED** [review]

**Comment by alexandresanlim** [comment]
does the configuration have a problem? because now [return error](https://github.com/snpptsdev/snppts/runs/513766529).
@ionixjunior help?

**Comment by ionixjunior** [comment]
Hi @alexandresanlim, sorry about that :( 

Based on this erros, I believe that the problem is in exception handling:

image

The line 79 of SnippetsTests.cs file try to cast the `WebException` to `HttpWebResponse` and access the `Response` attribute to get the value. I guess that I disconsidered some problems that can occurs. A refactor can be useful in this point. 

I will try simulate it ASAP and fix this to make this code more securely. Thanks for the report!

**Comment by jfversluis** [comment]
Added some code to overcome this and also see which feed is failing, at least at that point :)

**Comment by ionixjunior** [comment]
@jfversluis thank you!

**Pull request merged**
