### PR TITLE
Fix paging on category pages

### LINKED ISSUE #105: [Bug] Paging doesn't work on Category page
Paging works on the main page, but not per category. The link is just the same and page is reloaded.

### PR DESCRIPTION
**Pull request by immora**
Fixes #105 

I was quite annoyed by this bug that I can't browse all the snippets, but with this small change it all works like it should again :)

I also formatted the view nicely.

### CODE REVIEW

**Comment by jfversluis** [comment]
Thanks for the PR! I don't see how this fixes it though? I merged it, but it doesn't seem to fix anything :)

**Comment by jfversluis** [comment]
Maybe I spoke to soon, I see the deployment didn't happen. Let me see

**Comment by jfversluis** [comment]
OK no, this doesn't work. Actually breaks the whole site.

**Comment by immora** [comment]
@jfversluis do you know what might be the problem that it breaks the whole site? It's quite strange as I only changed the action name method and formatting?

And for me locally this fixes the paging:
snppts

**Comment by jfversluis** [comment]
Strange indeed, I just get a infinite redirection loop when it's deployed

**Comment by immora** [comment]
I even tried on different operating system and this still works :D  Can you tell me how you deploy and when exactly it happens?

**Comment by jfversluis** [comment]
@immora yeah it was something that wasn't showing locally, but it was a different problem than your code.

Sorry for the confusion and thank you so much for your contribution!

**Pull request merged**
