### PR TITLE
Link checker snippet

### PR DESCRIPTION
**Pull request by nogginbox**
## Submission description

This is a screenshot of the summary page from my work in progress app Link Checker. It uses the open source charts library [LiveCharts2 for MAUI](https://lvcharts.com/) to make a nice pie chart.

There's still work to do on the app. I will probably make some visual changes to the chart, so may update this PR, or add some more snippets if there are other places in the app I'd like to show off.

Screenshot of pie chart

### CODE REVIEW

**Comment by nogginbox** [comment]
The tests are failing due to this:
```
Image https://camo.githubusercontent.com/dfe2ebb45ee5071331ddd836f4048d545d67ec0644eeb0f9d5b2a615abdd0cf5/68747470733a2f2f766c616469736c6176616e746f6e79756b2e736972762e636f6d2f766c616469736c6176616e746f6e79756b2f61727469636c65732f32332f646f746e65742d6d6175692d62616e6b2d6170702e676966 is not reachable
Expected: OK
But was:  BadGateway
  ```
  
  But I didn't add that image. So I think it must have gone bad since it was added by someone else.

The image is from the MAUI BANK app by @VladislavAntonyuk

**Comment by VladislavAntonyuk** [comment]
try this image: 
`https://ik.imagekit.io/VladislavAntonyuk/vladislavantonyuk/articles/23/dotnet-maui-bank-app.gif`

**Review by jfversluis — APPROVED** [review]
Amazing! Thank you so much for adding this!

**Comment by nogginbox** [comment]
@jfversluis Thanks for approving and adding to [SNPPTS](https://www.snppts.dev/). I'll update it as the app gets more polished and maybe add some more, although the chart page is the most interesting visually.

Could you tag this repo with the topic hacktoberfest so people adding to it will their PR accepted towards [Hactoberfest](https://hacktoberfest.com/participation/). I missed out last year by one PR.

**Pull request merged**
