### PR TITLE
Add WeatherXam snippet

### PR DESCRIPTION
**Pull request by abdoulayedong**
*Thanks for submitting a PR to the Snppts ✂️ library!*

## Submission description

_Use this area to describe your submission. Screenshots are appreciated and GIFs (with a hard "g") will get bonus points!_

### Possible platform improvements

_Missing something on the platform? Let us know here._

### .NET MAUI Beautiful UI Challenge (August 2022)

If you're submitting this during August 2022, you can enter in the [.NET MAUI Beautiful UI Challenge](https://aka.ms/maui/uichallenge)! After submitting your pull request, grab the URL and fill out the quick form at https://www.surveymonkey.com/r/maui-ui-challenge to let us know where to send your stickers!

### CODE REVIEW

**Review by jfversluis — APPROVED** [review]
Whoa this looks pretty cool Abdoulaye!

Thank you so much!

**Comment by abdoulayedong** [comment]
Thank you very much. You are welcome. Just one thing i wanted to know where is the form to fill in to receive the stickers? 😅

**Comment by jfversluis** [comment]
Right here: https://www.surveymonkey.com/r/maui-ui-challenge

Not sure if this one counts though since it's Xamarin.Forms and not .NET MAUI ;)

**Comment by abdoulayedong** [comment]
ah ok I had misunderstood that despite the name of the challenge but hey it was cool to participate. thank you

**Comment by jfversluis** [comment]
@AizenDong just fill out the form, you might get lucky!

**Pull request merged**
